version: '3'
services:
  salt-master:
    image: ghcr.io/cdalvaro/docker-salt-master:latest
    container_name: salt-master
    ports:
      - '4505:4505'
      - '4506:4506'
    volumes:
      - './roots/:/home/salt/data/srv/'
      - './keys/:/home/salt/data/keys/'
      - './logs/:/home/salt/data/logs/'

  salt-minion:
    image: jarfil/salt-minion
    container_name: salt-minion
    environment:
      - SALT_MASTER=salt-master
    depends_on:
      - salt-master
